### ISSUE TITLE
Breaking of one-to-one relationships does not work

### ISSUE THREAD

**Issue by PrimozRome** [fuel/orm#135]
The scenario: Model_Article has one Model_Gallery ... 

```
$article = Model_Article::find(1);
$article->gallery = Model_Gallery::find(2); //will establish has one relationship
$article->save();
```

The problem comes when trying to break this relationship.

```
$article = Model_Article::find(1);
$article->delete(); // will delete article, but wont set 'article_id' field in gallery to null
```

Neither this will break relationship

```
$article = Model_Article::find(1);
$article->gallery = null;
$article->save();    // according to docs this should break relationship, but it doesn't
```

**Comment by KirillArtemenko** [comment]
And now when i need to delete related model i do

$gallery->articles[$article_id]->delete();

and need to do this

unset($gallery->articles[$article_id]);

if i dont do it save method add new article model in DB

$gallery->save();

**Comment by WanWizard** [comment]
@PrimozRome @kirillartemenko This should fix this issue. Could you test this and report the result?

**Comment by PrimozRome** [comment]
@WanWizard for me it still doesn't work. $this->gallery = null won't brake one-to-one the relationship!

$gallery = Model_Gallery::find(Input::post('gallery_id'));
if($gallery) {
    $article->gallery = $gallery;
}
else {
    $article->gallery = null;
}

**Comment by WanWizard** [comment]
This is a different issue.

The problem here is that the original related record isn't fetched, so the ORM is not aware of it. Therefore setting it to null doesn't change anything. It would if you would first load the original relation, and then set it to null.

I've tried to fix this for many-to-many relations in another issue, and ran into the problem of inconsistency because all loaded records are cached by the ORM. If you run an update query to reset foreign keys on records that are in cache, the cache becomes inconsistent. We haven't found a fix for this issue, but are looking into it.

This problem affects all relation types.
